webtalk_init -webtalk_dir C:/Users/matth/Documents/ECE 369A Computer Fundamentals/FinalProject/FinalProject.sim/sim_1/impl/func/xsim/xsim.dir/Datapath_tb_func_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec  4 12:59:21 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "143af0f9-e3b5-48a6-811e-f8e0ad6af04c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "88b0f248013047e4a8eb7b2f4844baa8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "79" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "28750 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "35.66_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "39632_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2222234917 -regid "" -xml C:/Users/matth/Documents/ECE 369A Computer Fundamentals/FinalProject/FinalProject.sim/sim_1/impl/func/xsim/xsim.dir/Datapath_tb_func_impl/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/matth/Documents/ECE 369A Computer Fundamentals/FinalProject/FinalProject.sim/sim_1/impl/func/xsim/xsim.dir/Datapath_tb_func_impl/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/matth/Documents/ECE 369A Computer Fundamentals/FinalProject/FinalProject.sim/sim_1/impl/func/xsim/xsim.dir/Datapath_tb_func_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
