# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/matth/Documents/ECE369A_ComputerFundamentals/FinalProject/FinalProject.cache/wt [current_project]
set_property parent.project_path C:/Users/matth/Documents/ECE369A_ComputerFundamentals/FinalProject/FinalProject.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/matth/Documents/ECE369A_ComputerFundamentals/FinalProject/FinalProject.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/matth/Documents/ECE369A_ComputerFundamentals/FinalProject/Files for Labs 1-18/ALU32Bit.v}
  {C:/Users/matth/Documents/ECE369A_ComputerFundamentals/FinalProject/Files for Labs 1-18/BranchComparator.v}
  {C:/Users/matth/Documents/ECE369A_ComputerFundamentals/Digital Logic Files/ClkDiv.v}
  {C:/Users/matth/Documents/ECE369A_ComputerFundamentals/FinalProject/Files for Labs 1-18/Controller.v}
  {C:/Users/matth/Documents/ECE369A_ComputerFundamentals/FinalProject/Files for Labs 1-18/DataMemory.v}
  {C:/Users/matth/Documents/ECE369A_ComputerFundamentals/FinalProject/Files for Labs 1-18/EXMERegister.v}
  C:/Users/matth/Documents/ECE369A_ComputerFundamentals/FinalProject/FinalProject.srcs/sources_1/new/Forward.v
  C:/Users/matth/Documents/ECE369A_ComputerFundamentals/FinalProject/FinalProject.srcs/sources_1/new/HazardDetection.v
  {C:/Users/matth/Documents/ECE369A_ComputerFundamentals/FinalProject/Files for Labs 1-18/HiLoRegister.v}
  {C:/Users/matth/Documents/ECE369A_ComputerFundamentals/FinalProject/Files for Labs 1-18/IDEXRegister.v}
  {C:/Users/matth/Documents/ECE369A_ComputerFundamentals/FinalProject/Files for Labs 1-18/IFIDRegister.v}
  {C:/Users/matth/Documents/ECE369A_ComputerFundamentals/FinalProject/Files for Labs 1-18/InstructionMemory.v}
  {C:/Users/matth/Documents/ECE369A_ComputerFundamentals/FinalProject/Files for Labs 1-18/MEWBRegister.v}
  {C:/Users/matth/Documents/ECE369A_ComputerFundamentals/FinalProject/Files for Labs 1-18/Mux32Bit2To1.v}
  {C:/Users/matth/Documents/ECE369A_ComputerFundamentals/FinalProject/Files for Labs 1-18/Mux32Bit4To1.v}
  {C:/Users/matth/Documents/ECE369A_ComputerFundamentals/FinalProject/Files for Labs 1-18/Mux64Bit4To1.v}
  {C:/Users/matth/Documents/ECE369A_ComputerFundamentals/FinalProject/Files for Labs 1-18/PCAdder.v}
  {C:/Users/matth/Documents/ECE369A_ComputerFundamentals/FinalProject/Files for Labs 1-18/ProgramCounter.v}
  {C:/Users/matth/Documents/ECE369A_ComputerFundamentals/FinalProject/Files for Labs 1-18/RegisterFile.v}
  {C:/Users/matth/Documents/ECE369A_ComputerFundamentals/Digital Logic Files/SevenSegment.v}
  {C:/Users/matth/Documents/ECE369A_ComputerFundamentals/FinalProject/Files for Labs 1-18/SignExtension.v}
  {C:/Users/matth/Documents/ECE369A_ComputerFundamentals/FinalProject/Files for Labs 1-18/SignExtension8bit.v}
  {C:/Users/matth/Documents/ECE369A_ComputerFundamentals/Digital Logic Files/TwoDigitDisplay.v}
  {C:/Users/matth/Documents/ECE369A_ComputerFundamentals/FinalProject/Files for Labs 1-18/Datapath.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/matth/Documents/ECE369A_ComputerFundamentals/Labs 1-3/Two4DigitDisplay.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/matth/Documents/ECE369A_ComputerFundamentals/Labs 1-3/Two4DigitDisplay.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Datapath -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Datapath.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Datapath_utilization_synth.rpt -pb Datapath_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
